language: java
jdk:
  - openjdk7

before_install: git clone https://github.com/Superloup10/Wolf-s-addons.git
 - chmod +x gradlew
install: ./gradlew setupCIWorkspace -S
script: ./gradlew build -S

env:
  global:
    TERM=dumb